name: Build and test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout AltDSS-Rust
        uses: actions/checkout@v3s

      - name: Build and test
        run: ./scripts/build_linux_x64.sh